[build]
  command = "npm install --prefix netlify/functions/api && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

