// models/userSchema.js
const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  id: { type: Number, required: true, unique: true },
  username: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    minlength: 3,
    match: [/^[a-zA-Z0-9_-]+$/, 'Username can only contain letters, numbers, underscores, and hyphens'],
  },
  email: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    lowercase: true,
    match: [/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/, 'Please use a valid email address'],
  },
  password: { type: String, required: true },
  name: String,
  firstName: String,
  lastName: String,
  gender: String,
  age: String,
  location: String,
  city: String,
  country: String,
  state: String,
  postalCode: String,
  phoneNumber: String,
  numbersVisibility: { 
    type: String, 
    enum: ['all_users', 'subscribers_only', 'followers_only', 'non'], 
    default: 'all_users'
  },
  website: {
    twitter: { type: String, default: '' },
    instagram: { type: String, default: '' },
    youtube: { type: String, default: '' },
  },
  profilePicture: String,
  images: [String],
  videos: [String],
  createdAt: { type: Date, default: Date.now },
  subscribers: { type: Number, default: 0 },
  subscribersList: [String],
  posts: [{
    id: Number,
    text: String,
    username: String,
    timestamp: String,
    images: [String],
    videos: [String],
    likes: [String],
    comments: [{ id: String, username: String, text: String, timestamp: String }],
    views: Number,
    isPremium: { type: Boolean, default: false },
    hashtags: [String],
    userMentions: [String],
    isAdminPost: { type: Boolean, default: false },
    hasGoldenBadge: { type: Boolean, default: false },
  }],
  premiumContent: [{
    id: String,
    text: String,
    username: String,
    timestamp: String,
    images: [String],
    videos: [String],
    likes: [String],
    comments: [{
      id: String,
      username: String,
      text: String,
      timestamp: String
    }],
    views: { type: Number, default: 0 },
    hashtags: [String],
    userMentions: [String],
    isAdminPost: { type: Boolean, default: false },
    hasGoldenBadge: { type: Boolean, default: false },
  }],
  followers: [String],
  following: [String],
  premiumPricing: {
    weekly: { type: Number, default: 0 },
    monthly: { type: Number, default: 0 },
    yearly: { type: Number, default: 0 },
  },
  premiumPlans: [{ interval: String, planCode: String }],
  subscriptions: [String],
  bio: String,
  isAdmin: { type: Boolean, default: false },
  bankName: { type: String, default: '' },
  accountNumber: { type: String, default: '' },
  balance: { type: Number, default: 0 },
  messagesFromPremiumOnly: { type: Boolean, default: false },
  userType: { 
    type: String, 
    enum: ['content_creator', 'escort', 'both'], 
    default: 'content_creator' 
  },
  payoutRequests: [{
    id: String,
    amount: Number,
    bankName: String,
    accountNumber: String,
    status: { type: String, enum: ['pending', 'approved', 'rejected'], default: 'pending' },
    createdAt: { type: Date, default: Date.now },
    updatedAt: Date,
    adminNote: { type: String, default: '' },
  }],
  fcmTokens: [{ type: String, default: [] }],
  emailNotifications: { type: Boolean, default: true },
}, { collation: { locale: 'en', strength: 2 } });

userSchema.index({ username: 1, email: 1 });

module.exports = { userSchema };